Controllers/TrainsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace transWEB.Controllers
{
    public class TrainsController : Controller
    {
        // GET: Trains
        public ActionResult Index()
        {
            ////HttpWebRequest request = (HttpWebRequest)WebRequest.Create("http://railway1.hinet.net/ctno1.htm");
            //HttpWebRequest request = (HttpWebRequest)WebRequest.Create("http://railway1.hinet.net/csearch.htm");
            //HttpWebResponse reponse = (HttpWebResponse)request.GetResponse();
            //Stream dataStream = reponse.GetResponseStream();
            //StreamReader reader = new StreamReader(dataStream, Encoding.Default);
            //string streamString = reader.ReadToEnd();
            //ViewBag.TrainsHtml = streamString;
            ////return RedirectPermanent("http://railway1.hinet.net/csearch.htm");
            ////return Redirect("http://railway1.hinet.net/csearch.htm");
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("查詢剩餘車票", "Index", "Trains")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <hr />
        <footer>
            @RenderSection("trainsCSearch", required: false)
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>

        </footer>
    </div>

   
</body>
</html>